## Building MPS exactly

In this notebook I will practice how to codify vectors into MPS directly setting the values of each tensor.

In [2]:
# Prerequisites
import numpy as np
from seemps.state import MPS


def tensors2vector(tensors):
    mps = MPS(tensors)
    vector = mps.to_vector()
    return vector

### Example 1.

Codify the vector [1, 0, 0, 0]:

In [2]:
tensor_1 = np.zeros((1,2,1))
tensor_2 = np.zeros((1,2,1))

tensor_1[0,0,0] = 1
tensor_1[0,1,0] = 0
tensor_2[0,0,0] = 1
tensor_2[0,1,0] = 0

tensors = [tensor_1, tensor_2]
tensors2vector(tensors)

array([1., 0., 0., 0.])

Explanation: set only the bitstring {00} to 1, and the rest of the bitstrings {01}, {10} and {11} to 0.

### Example 2.

Codify the vector [1, 0, 0, 1]:

In [3]:
tensor_1 = np.zeros((1,2,2))
tensor_2 = np.zeros((2,2,1))

tensor_1[0,0,0] = 1
tensor_1[0,0,1] = 0
tensor_1[0,1,0] = 0
tensor_1[0,1,1] = 1
tensor_2[0,0,0] = 1
tensor_2[0,1,0] = 0
tensor_2[1,0,0] = 0
tensor_2[1,1,0] = 1

tensors = [tensor_1, tensor_2]
tensors2vector(tensors)

array([1., 0., 0., 1.])

Explanation: I need a larger bond dimension to specify separately the bits 00 and 11 on different 'channels'.

### Example 3.

Codify the vector [1, 0, 0, 0, 0, 0, 0, 1]:

(this allows for the construction of the trapezoidal quadrature with a lineal combination of two MPS).

In [4]:
tensor_1 = np.zeros((1,2,2))
tensor_2 = np.zeros((2,2,2))
tensor_3 = np.zeros((2,2,1))

tensor_1[0,0,0] = 1
tensor_1[0,0,1] = 0
tensor_1[0,1,0] = 0
tensor_1[0,1,1] = 1

tensor_2[0,0,0] = 1
tensor_2[0,0,1] = 0
tensor_2[0,1,0] = 0
tensor_2[0,1,1] = 0
tensor_2[1,0,0] = 0
tensor_2[1,0,1] = 0
tensor_2[1,1,0] = 0
tensor_2[1,1,1] = 1

tensor_3[0,0,0] = 1
tensor_3[0,1,0] = 0
tensor_3[1,0,0] = 0
tensor_3[1,1,0] = 1

tensors = [tensor_1, tensor_2, tensor_3]
tensors2vector(tensors)

array([1., 0., 0., 0., 0., 0., 0., 1.])

Explanation: I 'build a bridge' between the first and the third site.

### Trapezoidal quadrature

In [42]:
def trapezoidal_quadrature(sites):
    tensor_1 = np.zeros((1,2,3))
    tensor_bulk = np.zeros((3,2,3))
    tensor_2 = np.zeros((3,2,1))

    tensor_1[0,0,0] = 1
    tensor_1[0,1,1] = 1
    tensor_1[0,0,2] = 1
    tensor_1[0,1,2] = 1

    tensor_bulk[0,0,0] = 1
    tensor_bulk[1,1,1] = 1
    tensor_bulk[2,0,2] = 1
    tensor_bulk[2,1,2] = 1
    
    tensor_2[0,0,0] = -0.5
    tensor_2[1,1,0] = -0.5
    tensor_2[2,0,0] = 1
    tensor_2[2,1,0] = 1

    tensors = [tensor_1] + [tensor_bulk for _ in range(sites-2)] + [tensor_2]
    return tensors
tensors2vector(trapezoidal_quadrature(6))

array([0.5, 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ,
       1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ,
       1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ,
       1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ,
       1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 0.5])

### Example 4.

Codify the vector [1,0,0,1,0,0,0,0]

In [5]:
# Hint: bit positions
# [1,    0,    0,    1,    0,    0,    0,    0]
# [000,  001,  010,  011,  100,  101,  110, 111]
tensor_1 = np.zeros((1,2,2))
tensor_2 = np.zeros((2,2,2))
tensor_3 = np.zeros((2,2,1))

tensor_1[0,0,0] = 1
tensor_1[0,0,1] = 1
tensor_1[0,1,0] = 0
tensor_1[0,1,1] = 0

tensor_2[0,0,0] = 1
tensor_2[0,0,1] = 0
tensor_2[0,1,0] = 0
tensor_2[0,1,1] = 0
tensor_2[1,0,0] = 0
tensor_2[1,0,1] = 0
tensor_2[1,1,0] = 0
tensor_2[1,1,1] = 1

tensor_3[0,0,0] = 1
tensor_3[0,1,0] = 0
tensor_3[1,0,0] = 0
tensor_3[1,1,0] = 1

tensors = [tensor_1, tensor_2, tensor_3]
tensors2vector(tensors)

array([1., 0., 0., 1., 0., 0., 0., 0.])

### Example 5.

Codify the vector [1,0,0,1,0,0,1,0]

In [32]:
# Hint: bit positions
# [1,    0,    0,    1,    0,    0,    1,    0]
# [000,  001,  010,  011,  100,  101,  110, 111]
# I DID THIS WITH THE DETERMINISTIC FINITE AUTOMATA
tensor_1 = np.zeros((1,2,2))
tensor_2 = np.zeros((2,2,2))
tensor_3 = np.zeros((2,2,1))

tensor_1[0, 0, 0] = 1
tensor_1[0, 1, 1] = 1

tensor_2[0, 0, 0] = 1
tensor_2[0, 1, 1] = 1
tensor_2[1, 1, 0] = 1

tensor_3[0, 0, 0] = 1
tensor_3[0, 1, 0] = 0
tensor_3[1, 1, 0] = 1

tensors = [tensor_1, tensor_2, tensor_3]
tensors2vector(tensors)

array([1., 0., 0., 1., 0., 0., 1., 0.])

### Example 6.

Codify the vector [1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1]:

(this allows for the construction of the Simpson quadrature with a lineal combination of three MPS).

In [37]:
# Hint: bit positions
# [1,    0,    0,    1,    0,    0,    1,    0,    0,    1,    0,    0,    1,    0,    0,    1]
# [0000, 0001, 0010, 0011, 0100, 0101, 0110, 0111, 1000, 1001, 1010, 1011, 1100, 1101, 1110, 1111]
# Hint: I want a 1 when two contiguous bits are 1.
# Also, I want a 1 when the two last bits of the two contiguous elements are different.
# The pattern has to be encoded in the last two bits, as it is a 3-periodic repetition and the last two bits encode 4 values.
tensor_1 = np.zeros((1, 2, 2))
tensor_2 = np.zeros((2, 2, 3))
tensor_3 = np.zeros((3, 2, 2))
tensor_4 = np.zeros((2, 2, 1))

tensor_1[0,0,0] = 1
tensor_1[0,1,1] = 1

tensor_2[0,0,0] = 1
tensor_2[0,1,1] = 1
tensor_2[1,0,2] = 1
tensor_2[1,1,0] = 1

tensor_3[0,0,0] = 1
tensor_3[0,1,1] = 1
# tensor_3[1,0,2] = 1 DEAD END
tensor_3[1,1,0] = 1
tensor_3[2,0,1] = 1
# tensor_3[2,1,2] = 1 DEAD END

tensor_4[0,0,0] = 1
# tensor_4[0,1,1] = 1 ILLEGAL
# tensor_4[1,0,2] = 1 ILLEGAL
tensor_4[1,1,0] = 1
# tensor_4[2,0,1] = 1 ILLEGAL
# tensor_4[2,1,2] = 1 ILLEGAL

tensors = [tensor_1, tensor_2, tensor_3, tensor_4]
tensors2vector(tensors)

array([1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1.])

### ALGORITHM FOR ARBITRARY SITES

In [119]:
def periodic_3_mps(sites):
    if sites < 4:
        raise ValueError("Sites should be larger than 4.")
    tensor_1 = np.zeros((1,2,2))
    tensor_1[0,0,0] = 1
    tensor_1[0,1,1] = 1

    tensor_2 = np.zeros((2,2,3))
    tensor_2[0,0,0] = 1
    tensor_2[0,1,1] = 1
    tensor_2[1,0,2] = 1
    tensor_2[1,1,0] = 1

    tensor_bulk = np.zeros((3,2,3))
    tensor_bulk[0,0,0] = 1
    tensor_bulk[0,1,1] = 1
    tensor_bulk[1,0,2] = 1
    tensor_bulk[1,1,0] = 1
    tensor_bulk[2,0,1] = 1
    tensor_bulk[2,1,2] = 1

    tensor_3 = np.zeros((3,2,2))
    tensor_3[0,0,0] = 1
    tensor_3[0,1,1] = 1
    tensor_3[1,1,0] = 1
    tensor_3[2,0,1] = 1

    tensor_4 = np.zeros((2,2,1))
    tensor_4[0,0,0] = 1
    tensor_4[1,1,0] = 1

    tensors = [tensor_1, tensor_2] + [tensor_bulk for _ in range(sites - 4)] + [tensor_3, tensor_4]
    return tensors

tensors2vector(periodic_3_mps(5))

array([1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0.,
       0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0.])

### Simpson quadrature

In [3]:
def simpson_quadrature(sites):
    if sites == 2:
        tensor_1 = np.zeros((1,2,4))
        tensor_1[0,0,0] = 1
        tensor_1[0,1,1] = 1
        tensor_1[0,0,2] = 1
        tensor_1[0,1,3] = 1

        tensor_2 = np.zeros((4,2,1))
        tensor_2[0,0,0] = -1
        tensor_2[1,1,0] = -1
        tensor_2[2,0,0] = 2
        tensor_2[2,1,0] = 3
        tensor_2[3,0,0] = 3
        tensor_2[3,1,0] = 2
        tensors = [tensor_1, tensor_2]
        return tensors
    tensor_1 = np.zeros((1,2,4))
    tensor_1[0,0,0] = 1
    tensor_1[0,1,1] = 1
    tensor_1[0,0,2] = 1
    tensor_1[0,1,3] = 1

    tensor_2 = np.zeros((4,2,5))
    tensor_2[0,0,0] = 1
    tensor_2[1,1,1] = 1
    tensor_2[2,0,2] = 1
    tensor_2[2,1,3] = 1
    tensor_2[3,0,4] = 1
    tensor_2[3,1,2] = 1

    tensor_bulk = np.zeros((5,2,5))
    tensor_bulk[0,0,0] = 1
    tensor_bulk[1,1,1] = 1
    tensor_bulk[2,0,2] = 1
    tensor_bulk[2,1,3] = 1
    tensor_bulk[3,0,4] = 1
    tensor_bulk[3,1,2] = 1
    tensor_bulk[4,0,3] = 1
    tensor_bulk[4,1,4] = 1

    tensor_3 = np.zeros((5,2,1))
    tensor_3[0,0,0] = -1
    tensor_3[1,1,0] = -1
    tensor_3[2,0,0] = 2
    tensor_3[2,1,0] = 3
    tensor_3[3,0,0] = 3
    tensor_3[3,1,0] = 2
    tensor_3[4,0,0] = 3
    tensor_3[4,1,0] = 3

    tensors = [tensor_1, tensor_2] + [tensor_bulk for _ in range(sites - 3)] + [tensor_3]
    return tensors

tensors2vector(simpson_quadrature(4))

array([1., 3., 3., 2., 3., 3., 2., 3., 3., 2., 3., 3., 2., 3., 3., 1.])

### Example 7. Vector with periodicity 5.
Codify the vector [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0]:

In [48]:
tensor_1 = np.zeros((1, 2, 2))
tensor_2 = np.zeros((2, 2, 4))
tensor_3 = np.zeros((4, 2, 4))
tensor_4 = np.zeros((4, 2, 3))
tensor_5 = np.zeros((3, 2, 1))

tensor_1[0,0,0] = 1
tensor_1[0,1,1] = 1

tensor_2[0,0,0] = 1
tensor_2[0,1,1] = 1
tensor_2[1,0,2] = 1
tensor_2[1,1,3] = 1

tensor_3[0,0,0] = 1
tensor_3[0,1,1] = 1
tensor_3[1,0,2] = 1
tensor_3[1,1,3] = 1
# tensor_2[2,0,4] = 1 ILLEGAL
tensor_3[2,1,0] = 1
tensor_3[3,0,1] = 1
tensor_3[3,1,2] = 1
#tensor_3[4,0,3] = 1
#tensor_3[4,1,4] = 1

tensor_4[0,0,0] = 1
tensor_4[0,1,1] = 1
tensor_4[1,0,2] = 1
# tensor_4[1,1,3] = 1
# tensor_4[2,0,4] = 1
tensor_4[2,1,0] = 1
tensor_4[3,0,1] = 1
tensor_4[3,1,2] = 1
# tensor_4[4,0,3] = 1
# tensor_4[4,1,4] = 1

tensor_5[0,0,0] = 1
tensor_5[2,1,0] = 1

         
tensors = [tensor_1, tensor_2, tensor_3, tensor_4, tensor_5]
tensors2vector(tensors)

array([1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.])

In [129]:
def periodic_5_start_0_mps(sites):
    if sites < 6:
        raise ValueError("Sites should be larger than 4.")
    tensor_1 = np.zeros((1, 2, 2))
    tensor_1[0,0,0] = 1
    tensor_1[0,1,1] = 1

    tensor_2 = np.zeros((2, 2, 4))
    tensor_2[0,0,0] = 1
    tensor_2[0,1,1] = 1
    tensor_2[1,0,2] = 1
    tensor_2[1,1,3] = 1

    tensor_3 = np.zeros((4, 2, 5))
    tensor_3[0,0,0] = 1
    tensor_3[0,1,1] = 1
    tensor_3[1,0,2] = 1
    tensor_3[1,1,3] = 1
    tensor_3[2,0,4] = 1
    tensor_3[2,1,0] = 1
    tensor_3[3,0,1] = 1
    tensor_3[3,1,2] = 1

    tensor_bulk = np.zeros((5,2,5))
    tensor_bulk[0,0,0] = 1
    tensor_bulk[0,1,1] = 1
    tensor_bulk[1,0,2] = 1
    tensor_bulk[1,1,3] = 1
    tensor_bulk[2,0,4] = 1
    tensor_bulk[2,1,0] = 1
    tensor_bulk[3,0,1] = 1
    tensor_bulk[3,1,2] = 1
    tensor_bulk[4,0,3] = 1
    tensor_bulk[4,1,4] = 1

    tensor_4 = np.zeros((5,2,4))
    tensor_4[0,0,0] = 1
    tensor_4[0,1,1] = 1
    tensor_4[1,0,2] = 1
    tensor_4[1,1,3] = 1
    tensor_4[2,1,0] = 1
    tensor_4[3,0,1] = 1
    tensor_4[3,1,2] = 1
    tensor_4[4,0,3] = 1

    tensor_5 = np.zeros((4,2,3))
    tensor_5[0,0,0] = 1
    tensor_5[1,0,2] = 1
    tensor_5[2,1,0] = 1
    tensor_5[3,1,2] = 1

    tensor_6 = np.zeros((3,2,1))
    tensor_6[0,0,0] = 1
    tensor_6[2,1,0] = 1

    tensors = [tensor_1, tensor_2, tensor_3] + [tensor_bulk for _ in range(sites - 6)] + [tensor_4, tensor_5, tensor_6]
    return tensors

tensors2vector(periodic_5_start_0_mps(6))

array([1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.])

### Example 8. Vector divisible by 5 mod 1
Codify the vector [0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]:

In [136]:
tensor_1 = np.zeros((1, 2, 2))
tensor_2 = np.zeros((2, 2, 4))
tensor_3 = np.zeros((4, 2, 4))
tensor_4 = np.zeros((4, 2, 3))
tensor_5 = np.zeros((3, 2, 1))

tensor_1[0,0,1] = 1
tensor_1[0,1,0] = 1

tensor_2[0,0,1] = 1
tensor_2[0,1,0] = 1
tensor_2[1,0,3] = 1
tensor_2[1,1,2] = 1

tensor_3[0,0,1] = 1
tensor_3[0,1,0] = 1
tensor_3[1,0,3] = 1
tensor_3[1,1,2] = 1
tensor_3[2,0,0] = 1
# tensor_3[2,1,4] = 1 ILLEGAL
tensor_3[3,0,2] = 1
tensor_3[3,1,1] = 1

tensor_4[0,1,0] = 1
tensor_4[1,1,2] = 1
tensor_4[2,0,0] = 1
tensor_4[3,0,2] = 1

tensor_5[0,1,0] = 1
tensor_5[2,0,0] = 1

tensors = [tensor_1, tensor_2, tensor_3, tensor_4, tensor_5]
tensors2vector(tensors)


array([0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.])

In [137]:
def periodic_5_start_1_mps(sites):
    if sites < 6:
        raise ValueError("Sites should be larger than 4.")
    tensor_1 = np.zeros((1, 2, 2))
    tensor_1[0,0,1] = 1
    tensor_1[0,1,0] = 1 

    tensor_2 = np.zeros((2, 2, 4))
    tensor_2[0,0,1] = 1
    tensor_2[0,1,0] = 1
    tensor_2[1,0,3] = 1
    tensor_2[1,1,2] = 1

    tensor_3 = np.zeros((4, 2, 5))
    tensor_3[0,0,1] = 1
    tensor_3[0,1,0] = 1
    tensor_3[1,0,3] = 1
    tensor_3[1,1,2] = 1
    tensor_3[2,0,0] = 1
    tensor_3[2,1,4] = 1
    tensor_3[3,0,2] = 1
    tensor_3[3,1,1] = 1

    tensor_bulk = np.zeros((5,2,5))
    tensor_bulk[0,0,1] = 1
    tensor_bulk[0,1,0] = 1
    tensor_bulk[1,0,3] = 1
    tensor_bulk[1,1,2] = 1
    tensor_bulk[2,0,0] = 1
    tensor_bulk[2,1,4] = 1
    tensor_bulk[3,0,2] = 1
    tensor_bulk[3,1,1] = 1
    tensor_bulk[4,0,4] = 1
    tensor_bulk[4,1,3] = 1

    tensor_4 = np.zeros((5,2,4))
    tensor_4[0,0,1] = 1
    tensor_4[0,1,0] = 1
    tensor_4[1,0,3] = 1
    tensor_4[1,1,2] = 1
    tensor_4[2,0,0] = 1
    tensor_4[3,0,2] = 1
    tensor_4[3,1,1] = 1
    tensor_4[4,1,3] = 1

    tensor_5 = np.zeros((4,2,3))
    tensor_5[0,1,0] = 1
    tensor_5[1,1,2] = 1
    tensor_5[2,0,0] = 1
    tensor_5[3,0,2] = 1

    tensor_6 = np.zeros((3,2,1))
    tensor_6[0,1,0] = 1
    tensor_6[2,0,0] = 1

    tensors = [tensor_1, tensor_2, tensor_3] + [tensor_bulk for _ in range(sites - 6)] + [tensor_4, tensor_5, tensor_6]
    return tensors

tensors = periodic_5_start_1_mps(6)
tensors2vector(tensors)

array([0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.])

Adding bulk tensors changes the periodicity for some reason.

### Example 9. Vector divisible by 5 mod 2
Codify the vector [0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0]:

In [104]:
tensor_1 = np.zeros((1, 2, 3))
tensor_2 = np.zeros((3, 2, 5))
tensor_3 = np.zeros((5, 2, 5))
tensor_4 = np.zeros((5, 2, 4))
tensor_5 = np.zeros((4, 2, 1))

tensor_1[0,0,1] = 1
tensor_1[0,1,2] = 1

tensor_2[0,0,1] = 1
tensor_2[0,1,2] = 1
tensor_2[1,0,2] = 1
tensor_2[1,1,0] = 1
tensor_2[2,0,3] = 1
tensor_2[2,1,4] = 1

tensor_3[0,0,1] = 1
tensor_3[0,1,2] = 1
tensor_3[1,0,2] = 1
tensor_3[1,1,0] = 1
tensor_3[2,0,3] = 1
tensor_3[2,1,4] = 1
tensor_3[3,0,0] = 1
tensor_3[3,1,3] = 1
tensor_3[4,0,4] = 1
tensor_3[4,1,1] = 1

tensor_4[0,0,1] = 1
tensor_4[2,0,3] = 1
tensor_4[3,1,3] = 1
tensor_4[4,1,1] = 1

tensor_5[1,1,0] = 1
tensor_5[3,0,0] = 1

tensors = [tensor_1, tensor_2, tensor_3, tensor_4, tensor_5]
tensors2vector(tensors)

array([0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [116]:
def periodic_5_start_2_mps(sites):
    if sites < 4:
        raise ValueError("Sites should be larger than 4.")
    tensor_1 = np.zeros((1, 2, 3))
    tensor_2 = np.zeros((3, 2, 5))
    tensor_bulk = np.zeros((5, 2, 5))
    tensor_3 = np.zeros((5, 2, 4))
    tensor_4 = np.zeros((4, 2, 1))

    tensor_1[0,0,1] = 1
    tensor_1[0,1,2] = 1

    tensor_2[0,0,1] = 1
    tensor_2[0,1,2] = 1
    tensor_2[1,0,2] = 1
    tensor_2[1,1,0] = 1
    tensor_2[2,0,3] = 1
    tensor_2[2,1,4] = 1

    tensor_bulk[0,0,1] = 1
    tensor_bulk[0,1,2] = 1
    tensor_bulk[1,0,2] = 1
    tensor_bulk[1,1,0] = 1
    tensor_bulk[2,0,3] = 1
    tensor_bulk[2,1,4] = 1
    tensor_bulk[3,0,0] = 1
    tensor_bulk[3,1,3] = 1
    tensor_bulk[4,0,4] = 1
    tensor_bulk[4,1,1] = 1

    tensor_3[0,0,1] = 1
    tensor_3[2,0,3] = 1
    tensor_3[3,1,3] = 1
    tensor_3[4,1,1] = 1

    tensor_4[1,1,0] = 1
    tensor_4[3,0,0] = 1


    tensors = [tensor_1, tensor_2] + [tensor_bulk for _ in range(sites - 4)] + [tensor_3, tensor_4]
    return tensors

tensors2vector(periodic_5_start_2_mps(6))

array([0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.])

### Example 9. Vector divisible by 5 mod 4
Codify the vector [0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0]:

In [60]:
tensor_1 = np.zeros((1, 2, 3))
tensor_2 = np.zeros((3, 2, 5))
tensor_3 = np.zeros((5, 2, 5))
tensor_4 = np.zeros((5, 2, 4))
tensor_5 = np.zeros((4, 2, 1))

tensor_1[0,0,2] = 1
tensor_1[0,1,1] = 1

tensor_2[0,0,2] = 1
tensor_2[0,1,1] = 1
tensor_2[1,0,0] = 1
tensor_2[1,1,2] = 1
tensor_2[2,0,4] = 1
tensor_2[2,1,3] = 1

tensor_3[0,0,2] = 1
tensor_3[0,1,1] = 1
tensor_3[1,0,0] = 1
tensor_3[1,1,2] = 1
tensor_3[2,0,4] = 1
tensor_3[2,1,3] = 1
tensor_3[3,0,3] = 1
tensor_3[3,1,0] = 1
tensor_3[4,0,1] = 1
tensor_3[4,1,4] = 1

tensor_4[0,1,1] = 1
tensor_4[2,1,3] = 1
tensor_4[3,0,3] = 1
tensor_4[4,0,1] = 1

tensor_5[1,0,0] = 1
tensor_5[3,1,0] = 1

         
tensors = [tensor_1, tensor_2, tensor_3, tensor_4, tensor_5]
tensors2vector(tensors)

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.])

### Example 10. Unit cells

Codify the vector [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1]

1 if divisible by 3\
2 if divisible by 3 mod 1\
3 if divisible by 3 mod 2

In [24]:
tensor_1 = np.zeros((1,2,2))
tensor_2 = np.zeros((2,2,3))
tensor_3 = np.zeros((3,2,1))

tensor_1[0,0,0] = 1
tensor_1[0,1,1] = 1

tensor_2[0,0,0] = 1
tensor_2[0,1,1] = 1
tensor_2[1,0,2] = 1
tensor_2[1,1,0] = 1

tensor_3[0,0,0] = 1
tensor_3[0,1,0] = 2
tensor_3[1,0,0] = 3
tensor_3[1,1,0] = 1
tensor_3[2,0,0] = 2
tensor_3[2,1,0] = 3

tensors = [tensor_1, tensor_2, tensor_3]
tensors2vector(tensors)

array([1., 2., 3., 1., 2., 3., 1., 2.])

Method: DO NOT KILL ANY CHANNEL
Fill out the values of every channel at the last bit.

Encode the quadrature:

[38. 75. 50. 50. 75. 38. 75. 50. 50. 75. 38. 75. 50. 50. 75. 38.]

In [6]:
tensor_1 = np.zeros((1,2,2))
tensor_2 = np.zeros((2,2,4))
tensor_3 = np.zeros((4,2,6))
tensor_4 = np.zeros((6,2,1))

tensor_1[0,0,0] = 1
tensor_1[0,1,1] = 1

tensor_2[0,0,0] = 1
tensor_2[0,1,1] = 1
tensor_2[1,0,2] = 1
tensor_2[1,1,3] = 1

tensor_3[0,0,0] = 1
tensor_3[0,1,1] = 1
tensor_3[1,0,2] = 1
tensor_3[1,1,3] = 1
tensor_3[2,0,4] = 1
tensor_3[2,1,0] = 1
tensor_3[3,0,1] = 1
tensor_3[3,1,2] = 1
#tensor_3[4,0,3] = 1
#tensor_3[4,1,4] = 1

tensor_4[0,0,0] = 38
tensor_4[0,1,0] = 75
tensor_4[1,0,0] = 50
tensor_4[1,1,0] = 50
tensor_4[2,0,0] = 75
tensor_4[2,1,0] = 38
tensor_4[3,0,0] = 75
tensor_4[3,1,0] = 50
tensor_4[4,0,0] = 50
tensor_4[4,1,0] = 75

tensors = [tensor_1, tensor_2, tensor_3, tensor_4]
tensors2vector(tensors)

array([38., 75., 50., 50., 75., 38., 75., 50., 50., 75., 38., 75., 50.,
       50., 75., 38.])

Now adding the boundary condition (pass it through the channels 0 and 1, and sum 2 to every other channel)

In [11]:
tensor_1 = np.zeros((1,2,4))
tensor_2 = np.zeros((4,2,6))
tensor_3 = np.zeros((6,2,7))
tensor_bulk = np.zeros((7,2,7))
tensor_4 = np.zeros((7,2,1))

tensor_1[0,0,0] = 1
tensor_1[0,1,1] = 1
tensor_1[0,0,2] = 1
tensor_1[0,1,3] = 1

tensor_2[0,0,0] = 1
tensor_2[1,1,1] = 1
tensor_2[2,0,2] = 1
tensor_2[2,1,3] = 1
tensor_2[3,0,4] = 1
tensor_2[3,1,5] = 1

tensor_3[0,0,0] = 1
tensor_3[1,1,1] = 1
tensor_3[2,0,2] = 1
tensor_3[2,1,3] = 1
tensor_3[3,0,4] = 1
tensor_3[3,1,5] = 1
tensor_3[4,0,6] = 1
tensor_3[4,1,2] = 1
tensor_3[5,0,3] = 1
tensor_3[5,1,4] = 1

tensor_bulk[0,0,0] = 1
tensor_bulk[1,1,1] = 1
tensor_bulk[2,0,2] = 1
tensor_bulk[2,1,3] = 1
tensor_bulk[3,0,4] = 1
tensor_bulk[3,1,5] = 1
tensor_bulk[4,0,6] = 1
tensor_bulk[4,1,2] = 1
tensor_bulk[5,0,3] = 1
tensor_bulk[5,1,4] = 1
tensor_bulk[6,0,5] = 1
tensor_bulk[6,1,6] = 1

tensor_4[0,0,0] = -19
tensor_4[1,1,0] = -19
tensor_4[2,0,0] = 38
tensor_4[2,1,0] = 75
tensor_4[3,0,0] = 50
tensor_4[3,1,0] = 50
tensor_4[4,0,0] = 75
tensor_4[4,1,0] = 38
tensor_4[5,0,0] = 75
tensor_4[5,1,0] = 50
tensor_4[6,0,0] = 50
tensor_4[6,1,0] = 75

tensors = [tensor_1, tensor_2, tensor_3, tensor_bulk, tensor_bulk, tensor_bulk, tensor_bulk, tensor_4]
tensors2vector(tensors)

array([19., 75., 50., 50., 75., 38., 75., 50., 50., 75., 38., 75., 50.,
       50., 75., 38., 75., 50., 50., 75., 38., 75., 50., 50., 75., 38.,
       75., 50., 50., 75., 38., 75., 50., 50., 75., 38., 75., 50., 50.,
       75., 38., 75., 50., 50., 75., 38., 75., 50., 50., 75., 38., 75.,
       50., 50., 75., 38., 75., 50., 50., 75., 38., 75., 50., 50., 75.,
       38., 75., 50., 50., 75., 38., 75., 50., 50., 75., 38., 75., 50.,
       50., 75., 38., 75., 50., 50., 75., 38., 75., 50., 50., 75., 38.,
       75., 50., 50., 75., 38., 75., 50., 50., 75., 38., 75., 50., 50.,
       75., 38., 75., 50., 50., 75., 38., 75., 50., 50., 75., 38., 75.,
       50., 50., 75., 38., 75., 50., 50., 75., 38., 75., 50., 50., 75.,
       38., 75., 50., 50., 75., 38., 75., 50., 50., 75., 38., 75., 50.,
       50., 75., 38., 75., 50., 50., 75., 38., 75., 50., 50., 75., 38.,
       75., 50., 50., 75., 38., 75., 50., 50., 75., 38., 75., 50., 50.,
       75., 38., 75., 50., 50., 75., 38., 75., 50., 50., 75., 38

Note: it is not worth it. I think it is better to subtract the boundary after.

In [45]:
tensor_1 = np.zeros((1,2,2))
tensor_2 = np.zeros((2,2,2))
tensor_3 = np.zeros((2,2,1))

tensor_1[0,0,0] = 1
tensor_1[0,0,1] = 0
tensor_1[0,1,0] = 0
tensor_1[0,1,1] = 1

tensor_2[0,0,0] = 1
tensor_2[0,0,1] = 0
tensor_2[0,1,0] = 0
tensor_2[0,1,1] = 0
tensor_2[1,0,0] = 0
tensor_2[1,0,1] = 0
tensor_2[1,1,0] = 0
tensor_2[1,1,1] = 1

tensor_3[0,0,0] = 1
tensor_3[0,1,0] = 0
tensor_3[1,0,0] = 0
tensor_3[1,1,0] = 1

tensors = [tensor_1, tensor_2, tensor_3]
tensors2vector(tensors)

array([1., 0., 0., 0., 0., 0., 0., 1.])